# Generated by Django 3.0.3 on 2020-02-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikesCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='likes.Post')),
            ],
        ),
    ]
