# Generated by Django 3.0.3 on 2020-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='LikesCounter',
        ),
    ]
