# Generated by Django 3.0.3 on 2020-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200209_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('p', 'Post'), ('n', 'News')], help_text='Is it news or post?', max_length=1, null=True),
        ),
    ]
