# Generated by Django 3.0.3 on 2020-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('p', 'Post'), ('n', 'News')], default='n', help_text='Is it news or post?', max_length=1, null=True),
        ),
    ]
